//pluginManagement {
//    repositories {
//        google()
//        mavenCentral()
//        gradlePluginPortal()
//    }
//}
//dependencyResolutionManagement {
//    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
//    repositories {
//        google()
//        mavenCentral()
//    }
//}
rootProject.name = "HahaLearn"
include ':app'
include ':BluetoothSdk'
//include ':starrysky'
include ':ServiceAnnotationProcessor'
include ':ServiceAnnotation'
include ':ServiceApi'
include ':ServiceImpl'
include ':ServiceAnnotationRuntime'
include ':pluginapp'
//include ':ServiceRouter'
//include ':ServiceRouterProcessor'
//include ':ServiceRouterAnnotation'
//include ':ServiceRouterUtils'
// 引入 Flutter 模块
include ':fluttertest'
//project(':fluttertest').projectDir = file('../fluttertest/.android/include_flutter.groovy') // 注意路径

setBinding(new Binding([gradle: this]))
evaluate(new File(
        settingsDir,
        'fluttertest/.android/include_flutter.groovy'
))