plugins {
    id 'java-library'
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.jvm'
}
java {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'com.squareup:javapoet:1.13.0'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
}