plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-android'
}

android {
    namespace 'com.haha.serviceruntime'
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility rootProject.ext.sourceCompatibility_javaVersion
        targetCompatibility rootProject.ext.targetCompatibility_javaVersion
    }
    kotlinOptions {
        jvmTarget = rootProject.ext.jvmTarget_version
    }
}

dependencies {
    api project(':ServiceAnnotation')
    api project(':ServiceApi')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
