plugins {
    id 'java-library'
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.annotation:annotation-jvm:1.9.1'
    implementation project(":ServiceRouterAnnotation")
}